retire electron-prebuilt
electron-userland/electron-prebuilt pull request #275
Opened 2017-08-08 21:07 UTC by zeke

The `electron` module will now be published to npm as part of the Electron release process, obviating the need for `electron-prebuilt` and the `electron-prebuilt-updater` Heroku app. This repo's history has been imported wholesale into electron/electron. See https://github.com/electron/electron/pull/10172 for technical details.

This PR updates the README with info about the change and adds some backstory so people know what the role of this repo was in the past, and why we made the change.

2017-08-08 21:27 UTC, jkleinsc requested changes
Looks good to me except for the small grammatical correction needed.

2017-08-08 21:27 UTC, jkleinsc commented on README.md
> +it's been challening to work these additions into the `electron` -> `electron-prebuilt-updater` -> `electron-prebuilt` release flow.
`it's been challening` should be `it's been challenging`

2017-08-08 21:30 UTC, vanessayuenn commented
I love the `back story` section! 👍

2017-08-08 21:31 UTC, vanessayuenn approved these changes

2017-08-08 21:34 UTC, kevinsawicki approved these changes
LGTM

2017-08-08 22:30 UTC, zeke commented
Update: Closed all open issues, encouraging folks to open followup issues on electron/electron if needed.

2017-08-09 22:04 UTC, malept commented
It'd be nice if there was a bot that auto-closed new issues/PRs (with roughly the same message as @zeke's), but not required.

2017-08-09 22:47 UTC, zeke commented
> people have a tendency to automatically delete PR/issue template text

Let's wait it out and see.

> It'd be nice if there was a bot that auto-closed new issues/PRs

WIP here: https://github.com/electron/electron-probot

2017-08-09 22:56 UTC, malept commented
> WIP here: https://github.com/electron/electron-probot

I think it's currently private.

2017-08-09 22:59 UTC, zeke commented
🔒 🔨

2017-08-14 15:41 UTC, merged